lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["java.lang:type=Memory", "java.lang:type=OperatingSystem", "java.lang:type=Threading"]
jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:9099/jmxrmi
rules:
- pattern: ".*"