receivers:
  otlp:
    protocols:
      otlp: "localhost:4018"

exporters:
  prometheus:
    endpoint: "localhost:9316"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]