global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'squash-tm'
    static_configs:
      - targets: ['localhost:9316']
        labels:
          instance: squash-tm  # Common label
          job: otel_collector  # Label for OTel collector
  - job_name: 'jmx'
    static_configs:
      - targets: ['localhost:9033']
          instance: squash-tm  # Common label
          job: jmx_collector  # Label for OTel collector