global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'SquashTM-Metrics'
    scrape_interval: 15s
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['localhost:9009']
        labels:
          application: 'Squash TM'