global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'squash-tm'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'jmx'
    static_configs:
      - targets: ['localhost:9033']
